### ISSUE TITLE
Add autocomplete="off" and autocapitalize="off" attributes on input fields

### ISSUE THREAD

**Issue by ghost** [klenwell/mushpup#8]
iOS and probably other devices have a habit of autocapitalising and autocorrecting input fields, which isn't ideal when mushpup-style domains are case-sensitive and rarely dictionary friendly words.

input="url" should also make shortcuts to various .tld 's available on mobile

**Comment by klenwell** [comment]
@putty182 Thanks for the suggestions. I've noticed the autocorrecting issues on mobile and it is annoying. I didn't realize these attributes existed. I'll add them as soon as I have a chance.

**Comment by klenwell** [comment]
Assigned to Trello card:

- https://trello.com/c/p08cW1AC

**Comment by klenwell** [comment]
On disabling autocorrect attributes:

https://davidwalsh.name/disable-autocorrect
